{% set name = "pytalises" %}
{% set version = "0.1.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytalises-{{ version }}.tar.gz
  sha256: 224bfc1547c2e781e30ce37825f78e14163f07949bc30d43c76292829e34bd9d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - numba >=0.50
    - numexpr >=2.7
    - numpy >=1.19
    - pyfftw >=0.12
    - scipy >=1.5
  run:
    - numba >=0.50
    - numexpr >=2.7
    - numpy >=1.19
    - pyfftw >=0.12
    - scipy >=1.5

test:
  imports:
    - pytalises
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/savowe/pytalises
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: " TALISES (This Ain't a LInear Schrödinger Equation Solver) is an easy-to-use Python implementation of the Split-Step Fourier Method, for numeric calculation of a wave function's time-propagation under the Schrödinger equation."
  doc_url: https://pytalises.readthedocs.io
  dev_url: http://github.com/savowe/pytalises

extra:
  recipe-maintainers:
    - savowe
