{% set name = "pytalises" %}
{% set version = "0.1.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytalises-{{ version }}.tar.gz
  sha256: faa08e778bf498d1921c0a392c81aee6979a7477d41eccb22edab023feeb6df0
build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - llvmlite
    - numba >=0.50
    - numexpr
    - numpy >=1.17
    - pyfftw
    - python >=3.6
    - scipy >=1.5

test:
  imports:
    - pytalises
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/savowe/pytalises
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: " TALISES (This Ain't a LInear Schrödinger Equation Solver) is an easy-to-use Python implementation of the Split-Step Fourier Method, for numeric calculation of a wave function's time-propagation under the Schrödinger equation."
  doc_url: https://pytalises.readthedocs.io
  dev_url: http://github.com/savowe/pytalises

extra:
  recipe-maintainers:
    - savowe
